services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: energy
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db-sql:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
